apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: k8s
  name: {{ .Values.service.name }}
  namespace: default
spec:
  ports:
  - name: web
    port: {{ .Values.service.port }}
    targetPort: web
  selector:
    app: prometheus
    prometheus: k8s
  sessionAffinity: ClientIP
