# Default values for node-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

service:
   name: node-exporter
   namespace: default
   port: 9100

ServiceAccountName: node-exporter

daemonSet:
   image: quay.io/prometheus/node-exporter:v0.18.1

ClusterRoleName: node-exporter


