apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: main
  name: {{ .Values.service.name }}
  namespace: default
spec:
  ports:
  - name: web
    port: {{ .Values.service.port }}
    targetPort: web
  selector:
    alertmanager: main
    app: alertmanager
  sessionAffinity: ClientIP
