apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: v0.18.1
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
spec:
  clusterIP: None
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: https
  selector:
    app.kubernetes.io/name: node-exporter
